spring.application.name=saadbr-bot
server.port=8087
spring.ai.openai.api-key=${OPENAI_API_KEY}
spring.ai.openai.chat.options.model=gpt-4o
spring.ai.mcp.client.streamable-http.connections.saadbr-mcp.url=http://localhost:6969/mcp
telegram.api.key=${TELEGRAM_API}
spring.datasource.url=jdbc:postgresql://localhost:5432/ragdb
spring.datasource.username=rag
spring.datasource.password=rag
spring.ai.vectorstore.pgvector.initialize-schema=true
spring.ai.openai.embedding.options.model=text-embedding-3-small
rag.ingest.on-startup=true
rag.ingest.skip-if-not-empty=true
spring.config.import=optional:configserver:http://localhost:9999
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
spring.cloud.config.fail-fast=false
spring.cloud.config.enabled=false
eureka.client.enabled=true
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.prefer-ip-address=true
eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka
logging.level.org.springframework.cloud.netflix.eureka=DEBUG
logging.level.com.netflix.discovery=DEBUG
eureka.client.jersey.enabled=false