spring.application.name=saadbr-bot
server.port=8087
spring.ai.openai.api-key=${OPENAI_API_KEY}
spring.ai.openai.chat.options.model=gpt-4o
spring.ai.mcp.client.streamable-http.connections.saadbr-mcp.url=http://localhost:6969/mcp
telegram.api.key=${TELEGRAM_API}